#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9981" \
        s6-applyuidgid -u $(id -u abc) -g $(id -g abc) /usr/bin/tvheadend -C -c /config $RUN_OPTS
